version: '3'

services:
    brevetsapp:
        build: brevets/.
        ports: 
          - "5002:5000"
        depends_on:
            - brevetsdb
        environment:
            MONGODB_HOSTNAME: brevetsdb
    brevetsdb:
        image: mongo:5.0.5
